// Package compose generates a docker-compose project from an azlocal Config.
package compose

import (
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"

	"github.com/DanielTangnes/azlocal/internal/config"
)

// Project is a minimal subset of the docker-compose v3 schema, enough
// for our purposes. It marshals as standard compose YAML.
type Project struct {
	Name     string             `yaml:"name,omitempty"`
	Services map[string]Service `yaml:"services"`
	Volumes  map[string]any     `yaml:"volumes,omitempty"`
	Networks map[string]any     `yaml:"networks,omitempty"`
}

type Service struct {
	Image       string            `yaml:"image,omitempty"`
	Build       any               `yaml:"build,omitempty"`
	Command     any               `yaml:"command,omitempty"`
	Ports       []string          `yaml:"ports,omitempty"`
	Environment map[string]string `yaml:"environment,omitempty"`
	Volumes     []string          `yaml:"volumes,omitempty"`
	DependsOn   any               `yaml:"depends_on,omitempty"`
	Healthcheck *Healthcheck      `yaml:"healthcheck,omitempty"`
	Restart     string            `yaml:"restart,omitempty"`
	Networks    []string          `yaml:"networks,omitempty"`
	Platform    string            `yaml:"platform,omitempty"`
}

type Healthcheck struct {
	Test        []string `yaml:"test"`
	Interval    string   `yaml:"interval,omitempty"`
	Timeout     string   `yaml:"timeout,omitempty"`
	Retries     int      `yaml:"retries,omitempty"`
	StartPeriod string   `yaml:"start_period,omitempty"`
}

// Generate builds a Project from an azlocal Config.
func Generate(cfg *config.Config) (*Project, error) {
	p := &Project{
		Name:     "azlocal",
		Services: map[string]Service{},
		Volumes:  map[string]any{},
		Networks: map[string]any{"azlocal": map[string]any{}},
	}

	s := cfg.Services
	storageEnabled := s.Blob != nil || s.Queue != nil || s.Table != nil

	if storageEnabled {
		p.Services["azurite"] = azuriteService(s)
		p.Volumes["azurite-data"] = nil
	}

	if s.Cosmos != nil {
		p.Services["cosmos"] = cosmosService(s.Cosmos)
		p.Volumes["cosmos-data"] = nil
	}

	if s.ServiceBus != nil {
		sb, sql := serviceBusServices(s.ServiceBus)
		p.Services["servicebus"] = sb
		p.Services["servicebus-sql"] = sql
		p.Volumes["servicebus-sql-data"] = nil
	}

	if len(p.Services) == 0 {
		return nil, fmt.Errorf("no enabled services in config")
	}
	return p, nil
}

func azuriteService(s config.Services) Service {
	blobPort := portOr(s.Blob, 10000)
	queuePort := 10001
	if s.Queue != nil && s.Queue.Port != 0 {
		queuePort = s.Queue.Port
	}
	tablePort := 10002
	if s.Table != nil && s.Table.Port != 0 {
		tablePort = s.Table.Port
	}
	return Service{
		Image: "mcr.microsoft.com/azure-storage/azurite:latest",
		Command: []string{
			"azurite",
			"--blobHost", "0.0.0.0",
			"--queueHost", "0.0.0.0",
			"--tableHost", "0.0.0.0",
			"--location", "/data",
		},
		Ports: []string{
			fmt.Sprintf("%d:10000", blobPort),
			fmt.Sprintf("%d:10001", queuePort),
			fmt.Sprintf("%d:10002", tablePort),
		},
		Volumes:  []string{"azurite-data:/data"},
		Networks: []string{"azlocal"},
		Restart:  "unless-stopped",
		Healthcheck: &Healthcheck{
			Test:     []string{"CMD-SHELL", "nc -z localhost 10000 || exit 1"},
			Interval: "5s",
			Timeout:  "3s",
			Retries:  10,
		},
	}
}

func cosmosService(c *config.CosmosService) Service {
	port := 8081
	if c.Port != 0 {
		port = c.Port
	}
	return Service{
		// Linux-based emulator (preview, but the only Linux option).
		Image: "mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest",
		Ports: []string{
			fmt.Sprintf("%d:8081", port),
			"10250-10255:10250-10255",
		},
		Environment: map[string]string{
			"AZURE_COSMOS_EMULATOR_PARTITION_COUNT":           "3",
			"AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE":   "true",
			"AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE":       "127.0.0.1",
		},
		Volumes:  []string{"cosmos-data:/tmp/cosmos/appdata"},
		Networks: []string{"azlocal"},
		Restart:  "unless-stopped",
		Healthcheck: &Healthcheck{
			Test:        []string{"CMD-SHELL", "curl -sk https://localhost:8081/_explorer/emulator.pem -o /dev/null || exit 1"},
			Interval:    "10s",
			Timeout:     "5s",
			Retries:     30,
			StartPeriod: "60s",
		},
	}
}

func serviceBusServices(_ *config.ServiceBusService) (Service, Service) {
	sb := Service{
		Image: "mcr.microsoft.com/azure-messaging/servicebus-emulator:latest",
		Ports: []string{
			"5672:5672",
			"5300:5300",
		},
		Environment: map[string]string{
			"ACCEPT_EULA":           "Y",
			"SQL_SERVER":            "servicebus-sql",
			"MSSQL_SA_PASSWORD":     "azlocalP@ssw0rd!",
			"SQL_WAIT_INTERVAL":     "5",
		},
		// A user-supplied Config.json describing queues/topics is mounted in;
		// generated by the seeder. For now we let the emulator start with defaults.
		DependsOn: map[string]map[string]string{
			"servicebus-sql": {"condition": "service_healthy"},
		},
		Networks: []string{"azlocal"},
		Restart:  "unless-stopped",
	}
	sql := Service{
		Image:    "mcr.microsoft.com/azure-sql-edge:latest",
		Platform: "linux/amd64",
		Environment: map[string]string{
			"ACCEPT_EULA": "Y",
			"MSSQL_SA_PASSWORD": "azlocalP@ssw0rd!",
		},
		Volumes:  []string{"servicebus-sql-data:/var/opt/mssql"},
		Networks: []string{"azlocal"},
		Restart:  "unless-stopped",
		Healthcheck: &Healthcheck{
			Test:     []string{"CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P azlocalP@ssw0rd! -Q 'SELECT 1' || exit 1"},
			Interval: "10s",
			Timeout:  "5s",
			Retries:  20,
		},
	}
	return sb, sql
}

// portOr returns the configured port for a Blob service, falling back to def.
func portOr(b *config.BlobService, def int) int {
	if b != nil && b.Port != 0 {
		return b.Port
	}
	return def
}

// Marshal serializes a Project to YAML bytes.
func Marshal(p *Project) ([]byte, error) {
	return yaml.Marshal(p)
}

// DefaultPath returns the path where azlocal writes the generated compose file.
func DefaultPath() string {
	return filepath.Join(".azlocal", "docker-compose.yaml")
}

// Write renders the project and writes it to DefaultPath, returning the path.
func Write(p *Project) (string, error) {
	out, err := Marshal(p)
	if err != nil {
		return "", err
	}
	path := DefaultPath()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return "", err
	}
	if err := os.WriteFile(path, out, 0o644); err != nil {
		return "", err
	}
	return path, nil
}
